CS2ERLCommander_node:
  ros__parameters:
    max_vel_error: .15
    max_pos_error: .05
    max_yaw_error: 0.078539816
    max_pitch_roll_error: .5 #0.157079632
    max_yank_steps: 200 # max_yank = (env.MAX_THRUST/env.CTRL_TIMESTEP)/max_yank_steps
    max_pitch_roll_rate_error: 1.0
    max_yaw_rate_error: 0.1